### ISSUE TITLE
won't build on fresh 14.04 from latest source

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#26]
following installation guide on clean 14.04 machine 

https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide

fails on step 1

[ 13%] Building CXX object open_ptrack/opt_utils/CMakeFiles/ros2udp_converter.dir/apps/ros2udp_converter.cpp.o
/home/opt/workspace/ros/catkin/src/open_ptrack/opt_utils/apps/ros2udp_converter.cpp:40:33: fatal error: opt_msgs/TrackArray.h: No such file or directory
 #include <opt_msgs/TrackArray.h>

and, indeed, I don't see TrackArray.h in github.
